# Generated by Django 3.2.8 on 2021-12-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuyen',
            fields=[
                ('MaTuyen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenTuyen', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LoTrinh',
            fields=[
                ('MaLT', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('XuatBen', models.DateTimeField()),
                ('CapBen', models.DateTimeField()),
                ('MaTuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tuyen')),
            ],
        ),
    ]
