from django.urls import path

from . import views
urlpatterns = [
    path('nv/<int:vtr>', views.inf_upd),
    path('nv/<int:vtr>/mnv/<str:mnv>', views.inf),
    path('nv/<int:vtr>/themnv', views.themnv),
    path('nv/<int:vtr>/them', views.add),
    path('nv/<int:vtr>/capnhat/<str:mnv>', views.update),
    path('usr/information', views.change_inf),
    path('usr/information/change', views.change),
    path('usr/changepassword', views.change_password),
    path('city_route/', views.city_route),
    path('city_route/add', views.city_route_add),
    path('city_route/information', views.city_route_inf_upd),
    path('city_route/information/<str:md>', views.city_route_change),
    path('city_route/information/<str:md>/change', views.city_route_update),
    path('sv_doimk', views.sv_doimk),
    path('route', views.route),
    path('route/add', views.route_add),
    path('bus_route/<str:mt>/update', views.bus_route_upd),
    path('route/selected', views.route_selected),
    path('route/selected/add', views.route_sel_add),
    path('route/information', views.route_information),
    path('route/<str:mt>', views.route_chitiet),
    path('bus_routes', views.bus_route),
    path('bus_routes/search', views.nvsv_search),
    path('bus_route/<str:mt>', views.bus_route_chitiet),
    path('route/<str:mt>/update', views.route_upd),
    path('route/<str:mt>/information', views.route_inf),
    path('ticket', views.ticket),
    path('ticket/cancel', views.cancel),
    path('ticket/search', views.ticket_search),
    path('checkMTD', views.checkMTD),
    path('checkMT', views.checkMT),
    path('nvtd/bus', views.bus),
    path('nvtd/bus_add', views.bus_add),
    path('nvtd/bus_update', views.bus_update),
    # path('nvtd/<str:mx>/bus_update', views.bus_update),
    path('nvtd/bus_infor', views.ds_bus),
    # path('nvtd/<str:mx>/bus_infor', views.ds_bus),
    path('nvtd/bus_inf', views.bus_infor),
]